"""Replay the scenario and assert what chapter 4's span produced."""

import inspect
import sys

from attr._compat import PY_3_13_PLUS
from attr._make import (
    NOTHING,
    _assign,
    _assign_with_converter,
    _determine_setters,
    _has_own_attribute,
    _make_init_script,
    fields,
)
from attrs import Factory, define


MODULE_MARKER = "module-level name visible to the generated __init__"


@define
class SomeClass:
    a_number: int = 42
    list_of_numbers: list[int] = Factory(list)

    def hard_math(self, another_number):
        return self.a_number + sum(self.list_of_numbers) * another_number


# --- the setter strategy chosen for a non-frozen, slotted class -------------
extra_lines, fmt_setter, fmt_setter_with_converter = _determine_setters(
    False, True, {}
)
assert extra_lines == ()
assert fmt_setter is _assign
assert fmt_setter_with_converter is _assign_with_converter
assert _assign("a_number", "a_number", False) == "self.a_number = a_number"

# --- the init script, rebuilt with the exact arguments from the trace ------
script, globs, annotations = _make_init_script(
    SomeClass,
    fields(SomeClass),
    False,  # pre_init
    False,  # pre_init_has_args
    False,  # post_init
    False,  # frozen
    True,  # slots
    False,  # cache_hash
    {},  # base_attr_map
    False,  # is_exc
    None,  # cls_on_setattr -- nulled by the builder in chapter 3
    attrs_init=False,
)

assert script == (
    "def __init__(self, a_number=attr_dict['a_number'].default,"
    " list_of_numbers=NOTHING):\n"
    "    self.a_number = a_number\n"
    "    if list_of_numbers is not NOTHING:\n"
    "        self.list_of_numbers = list_of_numbers\n"
    "    else:\n"
    "        self.list_of_numbers = __attr_factory_list_of_numbers()\n"
), script

assert annotations == {
    "return": None,
    "a_number": int,
    "list_of_numbers": list[int],
}

# The factory, the sentinel and the Attribute map the script needs.
assert globs["__attr_factory_list_of_numbers"] is list
assert globs["NOTHING"] is NOTHING
assert globs["attr_dict"]["a_number"] is fields(SomeClass).a_number
assert globs["attr_dict"]["a_number"].default == 42
# Not frozen and not hash-caching: no cached object.__setattr__ needed.
assert "_cached_setattr_get" not in globs
# The whole defining module got merged into the generated function's globals.
assert globs["MODULE_MARKER"] == MODULE_MARKER
assert globs is not sys.modules[SomeClass.__module__].__dict__

# --- the two protocols, added only because the class dict was vacant -------
class Plain:
    pass


assert _has_own_attribute(Plain, "__replace__") is False
assert _has_own_attribute(Plain, "__match_args__") is False

assert PY_3_13_PLUS is True  # the trace ran on an interpreter with __replace__
assert SomeClass.__replace__.__qualname__ == "SomeClass.__replace__"
assert SomeClass.__replace__.__module__ == SomeClass.__module__
assert "Method generated by attrs" in SomeClass.__replace__.__doc__

# field.name, not field.alias -- and only init, non-kw_only fields.
assert SomeClass.__match_args__ == ("a_number", "list_of_numbers")

# --- defaults are bound once, at def time; the factory is not -------------
sig = inspect.signature(SomeClass.__init__)
assert list(sig.parameters) == ["self", "a_number", "list_of_numbers"]
assert sig.parameters["a_number"].default == 42
assert sig.parameters["list_of_numbers"].default is NOTHING

print("chapter 4 holds")
