"""Replay the README scenario and assert what chapter 9's span produced.

Run from the repository root with PYTHONPATH=src.
"""

import linecache

from attr._make import ClassProps
from attrs import Factory, asdict, define, make_class


@define
class SomeClass:
    a_number: int = 42
    list_of_numbers: list[int] = Factory(list)

    def hard_math(self, another_number):
        return self.a_number + sum(self.list_of_numbers) * another_number


sc = SomeClass(1, [1, 2, 3])
assert repr(sc) == "SomeClass(a_number=1, list_of_numbers=[1, 2, 3])"
assert sc.hard_math(3) == 19
assert asdict(sc) == {"a_number": 1, "list_of_numbers": [1, 2, 3]}

C = make_class("C", ["a", "b"])

# --- the class was patched in place, not replaced by a slotted twin -------
assert "__slots__" in SomeClass.__dict__  # chapter 5: a brand-new type
assert "__slots__" not in C.__dict__  # chapter 9: the same type

props = C.__dict__["__attrs_props__"]
assert props.is_slotted is False
assert props.added_ordering is True
assert props.collected_fields_by_mro is False
assert props.on_setattr_hook is None
assert props.hashability is ClassProps.Hashability.UNHASHABLE

# added_pickling followed `slots`, so nothing was written for pickle.
assert props.added_pickling is False
assert "__getstate__" not in C.__dict__
assert "__setstate__" not in C.__dict__
# ...unlike the slotted class from chapters 3-5.
assert "__getstate__" in SomeClass.__dict__

# --- one compile(), one linecache entry, three functions ------------------
fname = f"<attrs generated methods {C.__module__}.C>"
assert C.__init__.__code__.co_filename == fname
assert C.__repr__.__code__.co_filename == fname
assert C.__eq__.__code__.co_filename == fname

src_lines = linecache.cache[fname][2]
assert "def __init__(self, a, b):\n" in src_lines
assert "    self.a = a\n" in src_lines
assert "    self.b = b\n" in src_lines

# The generated globals are the defining module's namespace, snapshotted.
assert C.__init__.__globals__["SomeClass"] is SomeClass

# _add_method_dunders_unsafe stamped the attached functions.
assert C.__repr__.__qualname__ == "C.__repr__"
assert C.__repr__.__doc__ == "Method generated by attrs for class C."

# --- what landed on the class ---------------------------------------------
assert tuple(a.name for a in C.__attrs_attrs__) == ("a", "b")
assert C.__match_args__ == ("a", "b")
assert C.__hash__ is None
assert C.__annotations__ == {}  # set by make_class *after* wrap returned

made = C("foo", "bar")
assert made.__dict__ == {"a": "foo", "b": "bar"}  # a dict class, not slotted
assert repr(made) == "C(a='foo', b='bar')"
assert C("foo", "bar") == made
assert (C("a", "a") < C("a", "b")) is True  # order=True added four methods

try:
    hash(made)
except TypeError:
    pass
else:
    raise AssertionError("C must be unhashable")

# --- the coda --------------------------------------------------------------
other = SomeClass(2, [3, 2, 1])
assert sc.__eq__(other) is False
assert sc.__ne__(other) is True

print("chapter 9 proof: ok")
